### ISSUE TITLE
Validate field string lengths with SQL limits

### ISSUE THREAD

**Issue by rymaju** [Code-4-Community/lucys-love-bus-backend#115]
Most of our SQL errors are errors with VARCHAR string lengths in our SQL schemas not being validated in our DTOs, we should add those string length checks on the DTO level for more informative error messages or not set a VARCHAR limit at all.

- [ ] Increase arbitrarily low VARCHAR limits to 255
- [ ] Validate all strings to match the limits we impose in the schema

**Comment by connernilsen** [comment]
See #117 for part 1 :)
